name: Analyze-Library

on:
  push:
    branches: [master]

jobs:
  lib-analysis:
    if: contains(github.event.head_commit.message, '[Start Analysis]')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
      - name: Execute analyzer
        run: |
          python ./rain_analyzer.py
      - name: Upload to Firebase Storage
        run: |
          curl -i -X POST -H "Content-Type: multipart/form-data" -F "data=@analyzer_output/rain_structure.json" https://firebasestorage.googleapis.com/v0/b/rainfall-firebase.appspot.com/o/rain_structure.json

